### ISSUE TITLE
Error in RawAlignment

### ISSUE THREAD

**Issue by JayGatsby91** [CasedUgr/KnowSeq#54]
I have acquired an SraRunInfo.csv from NCBI for the series of data I have. It was read into an 8 x 47 data.frame as 'data' using read.csv.

However, once I try to execute this R code:

rawAlignment(data,downloadRef='FALSE',downloadSamples='FALSE',createIndex='TRUE',BAMfiles='TRUE',SAMfiles='TRUE',countFiles='TRUE',referenceGenome=38,customFA='',customGTF='',fromGDC='FALSE',tokenPath='',manifestPath='')

I get the error:
Error in rawAlignment(data, downloadRef = "FALSE", downloadSamples = "FALSE",  :
  Please, use a string or character for the seq parameter.

Any help would be greatly appreciated.

R 4.0.3
Ubuntu 20.4

**Comment by CasedUgr** [comment]
Hello!

We have been checking the error and we have found the solution. Seq parameter is a deprecated parameter but it seems that it wasn't fully removed from the code. The rawAlignment function has been updated tonight to fix that mistake, just download and reinstall KnowSeq from the repository. Furthermore, the function has been adapted to changes in the HTSeq-count version, if you automatically downloaded the unixUtils folder just remove it to download it again. If you found any other issue just let us know! We are constantly improving our tool and  your feedback could be very useful.

Best,

Daniel

---
Ph. D. Daniel Castillo-Secilla
Post-Doctoral Researcher at Department of Architecture and Computer Technology (ATC)
The Higher Technical School of Information Technology and Telecommunications Engineering (ETSIIT)
Research Centre for Information and Communications Technologies of the University of Granada (CITIC) D1-7 Office
University of Granada, Spain
